/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stdio.h>
#include <stdint.h>
#include "stm32f4xx.h"
#include "uart.h"
#include "adxl345.h"

// Variables for storing accelerometer data
int16_t accel_x, accel_y, accel_z;
double accel_x_g, accel_y_g, accel_z_g;
uint8_t data_buffer[6];


// A simple bare-metal delay function to prevent UART spamming
void delay_ms(volatile uint32_t ms) {
    // Note: This is an estimation. 1000 roughly equals 1ms on a 16MHz default clock.
    for (uint32_t i = 0; i < (ms * 1000); i++) {
        __asm("NOP"); // No Operation (keeps compiler from optimizing loop away)
    }
}

int main(void)
{
    uart_init();
    adxl_init();

    while (1)
    {
        // Read accelerometer data starting from the data start register
        adxl_read(ADXL345_REG_DATA_START, data_buffer);

        // Combine high and low bytes to form the accelerometer data
        accel_x = (int16_t)((data_buffer[1] << 8) | data_buffer[0]);
        accel_y = (int16_t)((data_buffer[3] << 8) | data_buffer[2]);
        accel_z = (int16_t)((data_buffer[5] << 8) | data_buffer[4]);

        // Convert raw data to g values
        accel_x_g = accel_x * 0.0078;
        accel_y_g = accel_y * 0.0078;
        accel_z_g = accel_z * 0.0078;

        // Print values for debugging purposes
        // Using \n\r so the data scrolls down line by line
        printf("accel_x : %5d accel_y : %5d  accel_z : %5d\n\r", accel_x, accel_y, accel_z);

        // Add a 100ms delay to keep the terminal readable
        delay_ms(100);
    }

    return 0;
}
